(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"2008290323002",f:(function(AMP,_){
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var ca=ba(this);"function"===typeof Symbol&&Symbol("x");var da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;ea=ha.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ka=b.prototype};function ka(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function n(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ma="";
function p(){var a=self;if(a.__AMP_MODE)var b=a.__AMP_MODE;else{b=n(a.location.originalHash||a.location.hash);var c=n(a.location.search);ma||(ma=a.AMP_CONFIG&&a.AMP_CONFIG.v?a.AMP_CONFIG.v:"012008290323002");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(b.development)||a.AMP_DEV_MODE),examiner:"2"==b.development,esm:!1,geoOverride:b["amp-geo"],minified:!0,lite:void 0!=c.amp_lite,test:!1,log:b.log,version:"2008290323002",rtvVersion:ma};b=a.__AMP_MODE=b}return b}
;var na=Object.prototype.toString;function w(a){return a?Array.prototype.slice.call(a):[]}function x(a){return"[object Object]"===na.call(a)};var y=self.AMP_CONFIG||{},oa=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function pa(a){if(!self.document||!self.document.head||self.location&&oa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var z={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||pa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:oa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||pa("amp-geo-api")};function qa(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var A=self.__AMP_LOG;function B(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function D(){if(A.dev)return A.dev;throw Error("failed to call initLogConstructor");}
function E(a,b,c,d,e){return B().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var ra=Object.prototype.hasOwnProperty;function F(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function G(a){return a||{}}function H(a,b){if(ra.call(a,b))return a[b]}
function sa(a,b){var c=10;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.F=b.t;a.B=b.s;a.O=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.F!==a.B&&(a.O>c?Object.assign(a.F,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(ra.call(a.F,b)){var d=a.F[b];if(x(c)&&x(d)){e.push({t:d,s:c,d:a.O+1});return}}a.F[b]=c}}(a)));a={B:a.B,F:a.F,O:a.O}}};function I(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var J,ta="Webkit webkit Moz moz ms O o".split(" ");function ua(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function va(){return AMP.BaseElement.apply(this,arguments)||this}ja(va,AMP.BaseElement);k=va.prototype;k.getLayoutPriority=function(){return 1};k.isAlwaysFixed=function(){return!0};k.isLayoutSupported=function(){return!0};k.renderOutsideViewport=function(){return!0};k.L=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};var wa;function K(){return wa?wa:wa=Promise.resolve(void 0)};function L(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function xa(){this.va=100;this.W=this.aa=0;this.P=Object.create(null)}xa.prototype.has=function(a){return!!this.P[a]};xa.prototype.get=function(a){var b=this.P[a];if(b)return b.access=++this.W,b.payload};xa.prototype.put=function(a,b){this.has(a)||this.aa++;this.P[a]={payload:b,access:this.W};if(!(this.aa<=this.va)){D().warn("lru-cache","Trimming LRU cache");a=this.P;var c=this.W+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var g=d}}void 0!==g&&(delete a[g],this.aa--)}};var ya=G({c:!0,v:!0,a:!0,ad:!0}),za,Aa,Ba=/[?&]amp_js[^&]*/,Ca=/[?&]amp_gsa[^&]*/,Da=/[?&]amp_r[^&]*/,Ea=/[?&]amp_kit[^&]*/,Fa=/[?&]usqp[^&]*/;
function M(a){za||(za=self.document.createElement("a"),Aa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new xa));var b=Aa,c=za;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}
function Ga(a,b){var c=void 0===c?"source":c;E(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=M(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);E(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)}
function N(a){"string"==typeof a&&(a=M(a));return z.cdnProxyRegex.test(a.origin)}
function Ha(a){"string"==typeof a&&(a=M(a));if(!N(a))return a.href;var b=a.pathname.split("/");E(ya[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);E(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Ba,"").replace(Ca,"").replace(Da,"").replace(Ea,"").replace(Fa,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Ka(a,b){"string"==typeof b&&(b=M(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=M(d));c=c.replace(/\\/g,"/");var e=M(c);c=I(c.toLowerCase(),e.protocol)?e.href:I(c,"//")?d.protocol+c:I(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function La(a){var b=M(a),c=n(b.search);E(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Ma(a){if(a.__AMP__EXPERIMENT_TOGGLES)return a.__AMP__EXPERIMENT_TOGGLES;a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);var b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length){var e=a.AMP_CONFIG["allow-doc-opt-in"],g=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]');
if(g){var f=g.getAttribute("content").split(",");for(c=0;c<f.length;c++)-1!=e.indexOf(f[c])&&(b[f[c]]=!0)}}Object.assign(b,Na(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];a=n(a.location.originalHash||a.location.hash);for(var h=0;h<c.length;h++){var m=a["e-"+c[h]];"1"==m&&(b[c[h]]=!0);"0"==m&&(b[c[h]]=!1)}}return b}
function Na(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){D().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function Oa(a,b){var c=a.ownerDocument.defaultView,d=O(c),e=c!=d,g=!!Ma(d)["ampdoc-fie"];e&&!g?b=Pa(c,b)?P(c,b):null:(a=Q(a),a=R(a),b=Pa(a,b)?P(a,b):null);return b}function Qa(a,b){var c=O(a);Pa(a,"bind");if(Ma(c)["ampdoc-fie"]){var d=Q(a.document);Ra(R(d),d,"bind",function(){return b},!0)}else Ra(a,a,"bind",function(){return b}),P(a,"bind")}function S(a,b){a=O(a);return P(a,b)}function T(a,b){var c=Q(a);c=R(c);return P(c,b)}function O(a){return a.__AMP_TOP||(a.__AMP_TOP=a)}
function Q(a){return a.nodeType?S((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function R(a){a=Q(a);return a.isSingleDoc()?a.win:a}function P(a,b){Pa(a,b);a=Sa(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ra(a,b,c,d,e){var g=Sa(a),f=g[c];f||(f=g[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});if(e||!f.ctor&&!f.obj)f.ctor=d,f.context=b,f.resolve&&P(a,c)}
function Ta(a,b){var c=Ua(a,b);if(c)return c;a=Sa(a);a[b]=Va();return a[b].promise}function Ua(a,b){var c=Sa(a)[b];if(c){if(c.promise)return c.promise;P(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Sa(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function Pa(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Va(){var a=new L,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Wa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Xa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function Ya(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var g=d.setInterval(function(){b(a)&&(d.clearInterval(g),c())},5)}}function Za(a,b){Ya(a.documentElement,function(){return!!a.body},b)}function $a(a){return new Promise(function(b){return Za(a,b)})}function ab(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}
function bb(a,b){return a.closest?a.closest(b):ab(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function cb(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function db(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()}
function eb(a){I(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new L;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function fb(a){var b=Ua(R(a),"bind");if(b)return b;var c=Q(a);return c.waitForBodyOpen().then(function(){return gb(c.win,c.win.document.head)}).then(function(){var b=c.win;return b.__AMP_EXTENDED_ELEMENTS&&b.__AMP_EXTENDED_ELEMENTS["amp-bind"]?Ta(R(a),"bind"):null})}function hb(a){var b=Oa(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=O(b);return b!==c?ib(b):fb(a)}
function gb(a,b){if(b){var c={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var d=0;d<b.length;d++){var e=b[d];e=e.getAttribute("custom-element")||e.getAttribute("custom-template");c[e]=!0}c=Object.keys(c)}else c=[];return c.includes("amp-bind")?S(a,"extensions").waitForExtension(a,"amp-bind"):K()}
function ib(a){return $a(a.document).then(function(){return gb(a,a.document.head)}).then(function(){return a.__AMP_EXTENDED_ELEMENTS&&a.__AMP_EXTENDED_ELEMENTS["amp-bind"]?Ta(a,"bind"):null})};function jb(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function kb(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}}
function lb(a,b){var c=20;c=void 0===c?5:c;if(!isFinite(c)||0>c)throw Error("Invalid depth: "+c);if(a===b)return!0;for(a=[{a:a,b:b,depth:c}];0<a.length;){var d=a.shift();b=d.a;c=d.b;d=d.depth;if(0<d){if(typeof b!==typeof c)return!1;if(Array.isArray(b)&&Array.isArray(c)){if(b.length!==c.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:c[e],depth:d-1});continue}else if(b&&c&&"object"===typeof b&&"object"===typeof c){var g=Object.keys(b),f=Object.keys(c);if(g.length!==f.length)return!1;for(e=
0;e<g.length;e++){var h=g[e];a.push({a:b[h],b:c[h],depth:d-1})}continue}}if(b!==c)return!1}return!0};function mb(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,g=void 0===c.refresh?!1:c.refresh,f=void 0===c.xssiPrefix?void 0:c.xssiPrefix;Ga(b.getAttribute("src"),b);var h=S(a.win,"batched-xhr");return nb(b,e,g).then(function(a){return h.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(b){return S(a.win,"xhr").xssiJson(b,f)}).then(function(a){if(null==a)throw Error("Response is undefined.");return jb(a,d||".")}).catch(function(a){throw B().createError("failed fetching JSON data",
a);})}
function nb(a,b,c){var d=a.getAttribute("src"),e=Oa(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var g=e.collectDisallowedVarsSync(a);if(0<g.length)throw B().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(g.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")&&(h.credentials=a.getAttribute("credentials"));c&&
(h.cache="reload");return{xhrUrl:d,fetchOpt:h}})};function ob(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function pb(a){a=AMP.BaseElement.call(this,a)||this;a.R=void 0;a.$=new L;return a}ja(pb,AMP.BaseElement);k=pb.prototype;k.getLayoutPriority=function(){return 1};k.isAlwaysFixed=function(){return!0};k.isLayoutSupported=function(){return!0};
k.buildCallback=function(){var a=this;ua(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&hb(b).then(function(a){a.addOverridableKey(b.getAttribute("id"))});this.parseAndUpdate();this.element.hasAttribute("src")&&qb(this,!0);this.registerAction("refresh",function(){E(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');qb(a,!1,!0)})};
k.mutatedAttributesCallback=function(a){if(this.getAmpDoc().hasBeenVisible())void 0!==a.src&&this.element.hasAttribute("src")&&qb(this,!1);else{var b=this.L();D().error(b,"ampdoc must be visible before mutation.")}};k.renderOutsideViewport=function(){return!0};k.parseAndUpdate=function(){return void 0===this.R&&(this.R=rb(this),null!==this.R)?sb(this,this.R,!0):K()};
function rb(a){var b=a.element.children;if(0==b.length)return null;var c=a.L();if(1!=b.length)return a.user().error(c,"Should contain exactly one <script> child."),null;var d=b[0];return db(d)?kb(d.textContent,function(b){a.user().error(c,"Failed to parse state. Is it valid JSON?",b)}):(a.user().error(c,'State should be in a <script> tag with type="application/json".'),null)}
function wb(a,b,c){var d=a.element,e=a.getAmpDoc(),g=d.getAttribute("src");g=M(Ha(g)).origin===M(Ha(e.win.location)).origin||b?2:1;return mb(e,a.element,{urlReplacement:g,refresh:c}).catch(function(b){b=b?ob(a.win,"amp-state.error",G({response:b.response})):null;Oa(d,"action").trigger(d,"fetch-error",b,1)})}
function qb(a,b,c){b||(a.$=new L);var d=a.$;a.getAmpDoc().whenFirstVisible().then(function(){return wb(a,b,c)}).then(function(c){return sb(a,c,b)}).then(function(){return d.resolve()}).catch(function(a){d.resolve();throw a;})}k.getFetchingPromise=function(){return this.element.hasAttribute("src")?this.$.promise:K()};
function sb(a,b,c){if(void 0===b||null===b)return K();var d=E(a.element.id,"<amp-state> must have an id.");return hb(a.element).then(function(a){var e=F();e[d]=b;a.setState(e,{skipEval:c,skipAmpState:!c})})}k.L=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var xb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function yb(a){for(var b=[],c;c=xb.exec(a);){var d=c[1],e=void 0,g=void 0;if(c[2]){var f=c[3].toLowerCase();if("w"==f)e=parseInt(c[2],10);else if("x"==f)g=parseFloat(c[2]);else continue}else g=1;b.push({url:d,width:e,dpr:g})}return new zb(b)}
function zb(a){E(0<a.length,"Srcset must have at least one source");this.N=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}E(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?Ab:Bb);this.ra=b}
zb.prototype.select=function(a,b){if(this.ra){b*=a;a=this.N;for(var c=0,d=Infinity,e=Infinity,g=0;g<a.length;g++){var f=a[g].width,h=Math.abs(f-b);if(h<=1.1*d||1.2<b/e)c=g,d=h,e=f;else break}b=c}else{a=this.N;c=0;d=Infinity;for(e=0;e<a.length;e++)if(g=Math.abs(a[e].dpr-b),g<=d)c=e,d=g;else break;b=c}return this.N[b].url};zb.prototype.getUrls=function(){return this.N.map(function(a){return a.url})};
zb.prototype.stringify=function(a){for(var b=[],c=this.N,d=0;d<c.length;d++){var e=c[d],g=e.url;a&&(g=a(g));g=this.ra?g+(" "+e.width+"w"):g+(" "+e.dpr+"x");b.push(g)}return b.join(", ")};function Ab(a,b){E(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Bb(a,b){E(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Cb={"class":{denylistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},Db={width:null,height:null},Eb={"AMP-AUDIO":{album:null,artist:null,artwork:null,controlsList:null,loop:null,src:{allowedProtocols:{https:!0}},title:null},"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,
"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null,title:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,
https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-TWITTER":{"data-tweetid":null},"AMP-VIDEO":{album:null,alt:null,artist:null,artwork:null,attribution:null,controls:null,controlslist:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}},
title:null},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,geo:!0,http:!0,https:!0,mailto:!0,maps:!0,bip:!0,bbmi:!0,chrome:!0,"itms-services":!0,facetime:!0,"fb-me":!0,"fb-messenger":!0,intent:!0,line:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,webcal:!0,"web+mastodon":!0,wh:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,
accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{denylistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SECTION:{"data-expand":null},SELECT:{autofocus:null,disabled:null,
multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null,defaulttext:null}},Fb={src:!0,srcset:!0,href:!0,"xlink:href":!0};
function Gb(a){this.ta=a}Gb.prototype.canBind=function(a,b){return void 0!==Hb(this,a,b)};
Gb.prototype.isResultValid=function(a,b,c){var d=Hb(this,a,b);d&&d.alternativeName&&(d=Hb(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&H(Fb,b)){if("srcset"===b){try{var e=yb(c)}catch(h){return B().error("amp-bind","Failed to parse srcset: ",h),!1}var g=e.getUrls()}else g=[c];for(a=0;a<g.length;a++){a:{e=g[a];b=d;if(e){if(/__amp_source_origin/.test(e)){b=!1;break a}if(b=b.allowedProtocols)if(e=/^([^:\/?#.]+):[\s\S]*$/.exec(e),null!==e&&(e=e[1].toLowerCase().trim(),!ra.call(b,
e))){b=!1;break a}}b=!0}if(!b)return!1}}var f=d.denylistedValueRegex;return c&&f&&(new RegExp(f,"i")).test(c)?!1:!0};function Hb(a,b,c){if(I(c,"aria-"))return null;if(!H(Fb,c)||a.ta){var d=H(Cb,c);if(void 0!==d)return d;var e=H(Db,c);if(I(b,"AMP-")&&void 0!==e)return e;var g=H(Eb,b);if(g)return g[c]}};var Ib=!1;function Jb(a){if(!Ib){Ib=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var g=d.style;var f=c;if(I(f,"--"))g=f;else{J||(J=F());var h=J[f];if(!h){h=f;if(void 0===g[f]){var m=f;m=m.charAt(0).toUpperCase()+m.slice(1);b:{for(var t=0;t<ta.length;t++){var u=ta[t]+m;if(void 0!==g[u]){m=u;break b}}m=""}void 0!==g[m]&&(h=m)}J[f]=h}g=h}g&&(I(g,"--")?d.style.setProperty(g,e):d.style[g]=e)}}};function U(){this.o=[]}U.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=-1,d=0,e=this.o.length;d<=e;){c=Math.floor((d+e)/2);if(c===this.o.length)break;if(this.o[c].priority<b)d=c+1;else if(0<c&&this.o[c-1].priority>=b)e=c-1;else break}this.o.splice(c,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
U.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};ca.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var Kb=/nochunking=1/.test(self.location.hash),Lb=K();function Mb(a,b){if(Kb)Lb.then(b);else{var c=Nb,d=Q(a),e=R(d);Ra(e,d,"chunk",c);T(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.Y=a}function Ob(a,b){if("run"!=a.state){a.state="run";try{a.Y(b)}catch(c){throw a.la(),c;}}}V.prototype.L=function(){return this.Y.displayName||this.Y.name};V.prototype.la=function(){};V.prototype.ja=function(){return!1};V.prototype.pa=function(){return!1};function W(a,b,c){V.call(this,a);this.fa=c}
ja(W,V);W.prototype.la=function(){Jb(self.document)};W.prototype.ja=function(){return this.fa.ampdoc.isVisible()};W.prototype.pa=function(){return this.fa.ga};
function Nb(a){var b=this;this.ampdoc=a;this.h=a.win;this.K=new U;this.ea=this.ha.bind(this);this.H=0;this.T=!1;this.ua=this.h.document.documentElement.hasAttribute("i-amphtml-no-boilerplate");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.ha(null)});this.ga=!1;Ta(R(a),"viewer").then(function(){b.ga=!0});a.onVisibilityChanged(function(){a.isVisible()&&Pb(b)})}Nb.prototype.run=function(a,b){var c=new V(a);this.K.enqueue(c,b);Pb(this)};
Nb.prototype.runForStartup=function(a){a=new W(a,this.h,this);this.K.enqueue(a,Number.POSITIVE_INFINITY);Pb(this)};function Qb(a,b){for(var c=a.K.peek();c&&"not_run"!==c.state;)a.K.dequeue(),c=a.K.peek();c&&b&&a.K.dequeue();return c}
Nb.prototype.ha=function(a){var b=this,c=Qb(this,!0);if(!c)return this.T=!1,this.H=0,!1;try{var d=Date.now();Ob(c,a)}finally{Lb.then().then().then().then().then().then().then().then().then(function(){b.T=!1;b.H+=Date.now()-d;D().fine("CHUNK",c.L(),"Chunk duration",Date.now()-d,b.H);Pb(b)})}return!0};function Rb(a){a.ua&&5<a.H?(a.H=0,Sb(a)):Lb.then(function(){a.ea(null)})}function Pb(a){if(!a.T){var b=Qb(a);b&&(b.ja()?(a.T=!0,Rb(a)):b.pa()&&a.h.requestIdleCallback?Tb(a.h,a.ea):Sb(a))}}
function Sb(a){a.h.postMessage("amp-macro-task","*")}function Tb(a,b){function c(e){if(15>e.timeRemaining()){var g=2E3-(Date.now()-d);0>=g||e.didTimeout?(D().fine("CHUNK","Timed out",2E3,e.didTimeout),b(e)):(D().fine("CHUNK","Rescheduling with",g,e.timeRemaining()),a.requestIdleCallback(c,{timeout:g}))}else D().fine("CHUNK","Running idle callback with ",15),b(e)}var d=Date.now();a.requestIdleCallback(c,{timeout:2E3})};function Ub(){this.D=F();this.j=null}k=Ub.prototype;k.get=function(a){a=this.D[a];return null==a?null:a};k.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.D[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new L,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=F());this.j[a]=b}return b.promise};
k.signal=function(a,b){if(null==this.D[a]){var c=void 0==b?Date.now():b;this.D[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};k.rejectSignal=function(a,b){null==this.D[a]&&(this.D[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.promise.catch(function(){}),a.resolve=void 0,a.reject=void 0))};k.reset=function(a){this.D[a]&&delete this.D[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function Vb(a,b){function c(){d=0;var f=5E3-(a.Date.now()-e);if(0<f)d=a.setTimeout(c,f);else{var h=g;g=null;b.apply(null,h)}}var d=0,e=0,g=null;return function(b){for(var f=[],m=0;m<arguments.length;++m)f[m-0]=arguments[m];e=a.Date.now();g=f;d||(d=a.setTimeout(c,5E3))}};function Wb(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var g=a[e];b(g,e,a)?c.push(g):(d<e&&(a[d]=g),d++)}d<a.length&&(a.length=d)}function Xb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function Yb(){var a=p().esm?".mjs":".js";var b=z.cdn;return b+"/rtv/"+p().rtvVersion+"/ww"+a};function Zb(a){var b=this;this.h=a;this.Ea=S(a,"xhr");var c=Yb();D().fine("web-worker","Fetching web worker from",c);this.ba=null;this.ia=this.Ea.fetchText(c,{ampCors:!1,bypassInterceptorForDev:!1}).then(function(a){return a.text()}).then(function(d){d=d.replace(/^\/\/# sourceMappingURL=.*/,"//# sourceMappingURL="+(c+".map"));d=new a.Blob([d+"\n//# sourceurl="+c],{type:"text/javascript"});var e=a.URL.createObjectURL(d);b.ba=new a.Worker(e);b.ba.onmessage=b.Ca.bind(b)});this.S={};this.wa=0;this.sa=
[a]}function $b(a,b,c,d){return a.ia.then(function(){return new Promise(function(e,g){var f=a.wa++;a.S[f]={method:b,resolve:e,reject:g};e=d||a.h;g=a.sa.indexOf(e);e=0<=g?g:a.sa.push(e)-1;a.ba.postMessage({method:b,args:c,scope:e,id:f})})})}Zb.prototype.Ca=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.S[b];d?(d.resolve(c),delete this.S[b]):D().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
Zb.prototype.hasPendingMessages=function(){return 0<Object.keys(this.S).length};Zb.prototype.Fa=function(){return this.ia};function ac(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(a){return b.hasAttribute(a)})};function bc(){var a=cc();return function(b){return setTimeout(b,a())}}function cc(){var a=0;return function(){var b=Math.pow(1.5,a++);var c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var X=self.__AMP_ERRORS||[];self.__AMP_ERRORS=X;function dc(a){dc=bc();return dc(a)}function ec(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var fc;
function Y(a,b){try{if(a)if(void 0!==a.message)a=qa(a);else{var c=a;a=Error(ec(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),p().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?e.call(console,a.message,d):e.call(console,a.message)}d&&d.za&&
d.za("amp:error",a.message);gc.call(self,void 0,void 0,void 0,void 0,a)}}catch(g){setTimeout(function(){throw g;})}}function gc(a,b,c,d,e){var g=this;!this||!this.document||e&&e.expected||Jb(this.document);if(!p().development){var f=!1;try{f=hc()}catch(m){}if(!(f&&.01<Math.random())){var h=ic(a,b,c,d,e,f);h&&dc(function(){try{return jc(g,h).catch(function(){})}catch(m){}})}}}
function jc(a,b){return b.pt&&.9>Math.random()?K():kc(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",.1>Math.random()?z.betaErrorReporting:z.errorReporting,!0);c.send(JSON.stringify(b))}})}
function kc(a,b){var c=S(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);var d=c.getSingleDoc();if(!d.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var e=T(d,"viewer");return e.hasCapability("errorReporter")?e.isTrustedViewer().then(function(a){if(!a)return!1;e.sendMessage("error",G({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,pt:b.pt,jse:b.jse}));return!0}):Promise.resolve(!1)}
function ic(a,b,c,d,e,g){var f=a;e&&(f=e.message?e.message:String(e));f||(f="Unknown error");a=f;var h=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var m=!(self&&self.window),t=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||m)if(h=!0,.001<t)return;var u=0<=a.indexOf("\u200b\u200b\u200b");if(!(u&&.1<t)){f=Object.create(null);f.v=p().rtvVersion;f.noAmp=g?"1":"0";f.m=a.replace("\u200b\u200b\u200b","");f.a=u?"1":"0";f.ex=h?"1":"0";f.dw=m?"1":"0";var l="1p";self.context&&
self.context.location?(f["3p"]="1",l="3p"):p().runtime&&(l=p().runtime);f.rt=l;"inabox"===l&&(f.adid=p().a4aId);g=self;f.ca=g.AMP_CONFIG&&g.AMP_CONFIG.canary?"1":"0";g=self;f.bt=g.AMP_CONFIG&&g.AMP_CONFIG.type?g.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(f.or=self.location.ancestorOrigins[0]);self.viewerState&&(f.vs=self.viewerState);self.parent&&self.parent!=self&&(f.iem="1");if(self.AMP&&self.AMP.viewer){var q=self.AMP.viewer.getResolvedViewerUrl(),
C=self.AMP.viewer.maybeGetMessagingOrigin();q&&(f.rvu=q);C&&(f.mso=C)}fc||(fc=lc());f.jse=fc;var v=[];g=self.__AMP__EXPERIMENT_TOGGLES||null;for(var r in g)v.push(r+"="+(g[r]?"1":"0"));f.exps=v.join(",");e?(f.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(f.args=JSON.stringify(e.args)),u||e.ignoreStack||!e.stack||(f.s=e.stack),e.message&&(e.message+=" _reported_")):(f.f=b||"",f.l=c||"",f.c=d||"");f.r=self.document?self.document.referrer:"";f.ae=X.join(",");f.fr=self.location.originalHash||
self.location.hash;"production"===f.bt&&(f.pt="1");b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return f}}}function hc(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++)if(!N(a[b].src.toLowerCase()))return!0;return!1}
function lc(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(I(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(I(b,"Error: message"))return"Chrome"}return"unknown"};function mc(a,b,c){var d=self.location;La(c);var e=N(d),g=M(Ha(d));if("href"==b&&!I(c,"#"))return Ka(c,g);if("src"==b)return"amp-img"==a?nc(c,g,e):Ka(c,g);if("srcset"==b){try{var f=yb(c)}catch(h){return B().error("URL-REWRITE","Failed to parse srcset: ",h),c}return f.stringify(function(a){return nc(a,g,e)})}return c}
function nc(a,b,c){a=M(Ka(a,b));return"data:"==a.protocol||N(a)||!c?a.href:z.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};function oc(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function pc(a,b){var c=oc(a);if(c)b(a);else{var d=function(){oc(a)&&(c||(c=!0,b(a)),a.removeEventListener("readystatechange",d))};a.addEventListener("readystatechange",d)}}function qc(a){return new Promise(function(b){pc(a,b)})};var rc=/^(i?-)?amp(html)?-/,sc={INPUT:{checked:!0,value:!0},OPTION:{selected:!0},TEXTAREA:{text:!0}},tc=F({"AMP-CAROUSEL":["slide"],"AMP-LIST":["is-layout-container"],"AMP-SELECTOR":["selected"]}),uc=["AMP-LIST"];
function vc(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.I=b||a.win;this.X=[];this.Aa=Vb(this.h,function(){c.X.length=0});this.G=[];this.C=F();this.Z=T(a,"history");this.ma=[];this.J=1E3;this.ka=T(a,"mutator");this.w=F();this.Da=S(this.h,"timer");this.qa=null;this.V=T(this.ampdoc,"viewer");this.V.onMessageRespond("premutate",this.Ba.bind(this));this.na=a.whenFirstVisible().then(function(){if(b){var c=b.document;return qc(c).then(function(){return c})}return a.whenReady().then(function(){return a.getRootNode()})});
this.M=this.na.then(function(a){return wc(c,a)});this.da=new L;this.U=null;this.oa=new Ub;var d=self.AMP;d.printState=d.printState||this.ya.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.xa.bind(this)}vc.installInEmbedWindow=function(a,b){Qa(a,new vc(b,a))};k=vc.prototype;k.signals=function(){return this.oa};
k.setState=function(a,b){var c=this;b=void 0===b?{}:b;D().info("amp-bind","setState (init=%s):",b.skipEval,a);try{sa(this.w,a)}catch(d){B().error("amp-bind","Failed to merge result from AMP.setState().",d)}return b.skipEval?K():this.U=this.M.then(function(){return xc(c)}).then(function(a){return yc(c,a,{skipAmpState:b.skipAmpState,constrain:b.constrain})})};
k.invoke=function(a){var b=a.args,c=a.event,d=a.method,e=a.sequenceId,g=a.tagOrTarget;if(this.X.includes(e))return B().error("amp-bind","One state action allowed per event."),K();this.X.push(e);this.Aa();if(b=b.__AMP_OBJECT_STRING__){this.J=Math.min(2E3,Math.max(1E3,this.J+500));this.oa.signal("FIRST_MUTATE");var f={};c&&c.detail&&(f.event=c.detail);switch(d){case "setState":return this.setStateWithExpression(b,f);case "pushState":return this.pushStateWithExpression(b,f);default:return Promise.reject(D().createError("Unrecognized method: %s.%s",
g,d))}}else B().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return K()};k.setStateWithExpression=function(a,b){var c=this;return zc(this,a,b).then(function(a){return Ac(c,a)})};k.setStateWithObject=function(a){return(a=Bc(a))?Ac(this,a):Promise.reject("Invalid state")};
function Ac(a,b){D().info("amp-bind","setState:",b);a.U=a.setState(b).then(function(){return Cc(a)}).then(function(b){b&&a.Z.replace(b)});return a.U}k.pushStateWithExpression=function(a,b){var c=this;D().info("amp-bind","pushState:",a);return zc(this,a,b).then(function(a){function b(){return c.setState(d)}var d=F();Object.keys(a).forEach(function(a){d[a]=Bc(c.w[a])});return c.setState(a).then(function(){return Cc(c)}).then(function(a){c.Z.push(b,a)})})};
function Cc(a){var b=G({data:G({"amp-bind":a.w}),title:a.I.document.title});return a.V.isEmbedded()?a.V.isTrustedViewer().then(function(a){return a?b:null}):Promise.resolve(b)}k.rescan=function(a,b,c){var d=this;c=void 0===c?{}:c;return(c.fast?this.da.promise:this.M).then(function(){return d.Da.timeoutPromise(c.timeout||2E3,Dc(d,a,b,c),"Timed out waiting for amp-bind to rescan.")})};
function Dc(a,b,c,d){D().info("amp-bind","rescan: ",b,c,d);return(d.fast?Ec(a,b,c):Fc(a,b,c)).then(function(){if(d.update)return xc(a).then(function(c){return yc(a,c,{constrain:b,evaluateOnly:"evaluate"===d.update})})})}
function Ec(a,b,c){var d=Gc(a,c),e=[],g=b.filter(function(a){return a.hasAttribute("i-amphtml-binding")});b.forEach(function(a){a=a.querySelectorAll("[i-amphtml-binding]");Array.prototype.push.apply(g,a)});var f=a.J-a.numberOfBindings();for(b=0;b<g.length&&!Hc(a,g[b],f-e.length,e);b++);d.then(function(b){D().info("amp-bind","rescan.fast: delta=%s, total=%s",e.length-b,a.numberOfBindings())});return 0<e.length?Ic(a,e):K()}
k.getState=function(a){a=a?jb(this.w,a):void 0;return x(a)||Array.isArray(a)?Bc(a):a};k.getStateAsync=function(a){var b=this,c=/^[^.]*/.exec(a)[0];return this.na.then(function(d){var e=d.querySelector("#"+String(c).replace(Wa,Xa));if(!e)throw Error("#"+c+" does not exist.");return eb(e).then(function(a){return a.getImpl(!0)}).then(function(a){return a.getFetchingPromise()}).catch(function(){}).then(function(){return b.getState(a)})})};
k.getStateValue=function(a){a=jb(this.w,a);return void 0===a||null===a?null:x(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function wc(a,b){var c=!ac(a.I.document);a.qa=new Gb(c);return Z(a,"bind.init",[c]).then(function(){return Promise.all([Jc(a).then(function(){return a.da.resolve()}),Kc(a,[b])])}).then(function(){b.addEventListener("amp:dom-update",function(b){return Lc(a,b)})}).then(function(){var a=b.querySelectorAll("AMP-STATE"),c=w(a).map(function(a){return eb(a).then(function(){return a.getImpl(!1)}).then(function(a){return a.parseAndUpdate()})});return Promise.all(c)}).then(function(){a.V.sendMessage("bindReady",
void 0);if(p().development)return xc(a).then(function(b){return Mc(a,b)})})}k.numberOfBindings=function(){return this.G.reduce(function(a,b){return a+b.boundProperties.length},0)};k.Ia=function(a){this.J=a};k.Ga=function(){return this.Z};
k.Ba=function(a){var b=this,c=[];return this.M.then(function(){Object.keys(a.state).forEach(function(d){b.ma.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&B().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};k.addOverridableKey=function(a){this.ma.push(a)};
function Jc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];cb(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Nc(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function Kc(a,b){if(!b.length)return Promise.resolve(0);var c=b.map(function(b){var c=a.J-a.numberOfBindings();return Oc(a,b,c).then(function(b){var c=b.bindings;b.limitExceeded&&D().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.J);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?Ic(a,b):0})}
function Ic(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.C[b];0<d.length&&Nc(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function Gc(a,b){if(!b.length)return Promise.resolve(0);Wb(a.G,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.C){var e=a.C[d];Wb(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.C[d])}var g=c.length;return 0<g?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return g}):Promise.resolve(0)}
function Oc(a,b,c){function d(){var b=g.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!g.nextNode();Hc(a,b,c-e.length,e)&&(f=!0);if(uc.includes(b.nodeName))a:{for(b=g.currentNode;b;b=g.parentNode())if(b=g.nextSibling())break a;b=null}else b=g.nextNode();return!b||f}var e=[],g=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),f=!1;return new Promise(function(b){function c(g){var m=!1;if(g&&!g.didTimeout)for(;1<g.timeRemaining()&&
!m;)m=d();else for(g=0;250>g&&!m;g++)m=d();m?b({bindings:e,limitExceeded:f}):Mb(a.ampdoc,c)}Mb(a.ampdoc,c)})}function Hc(a,b,c,d){var e=!1,g=Pc(a,b);g.length>c&&(g.length=c,e=!0);0<g.length&&a.G.push({element:b,boundProperties:g});var f=b.tagName;g.forEach(function(c){var e=c.expressionString;d.push({tagName:f,property:c.property,expressionString:e});a.C[e]||(a.C[e]=[]);a.C[e].push(b)});return e}
function Pc(a,b){for(var c=[],d=b.attributes,e=0,g=d.length;e<g;e++){a:{var f=void 0,h=a,m=d[e];var t=b;var u=t.tagName,l=m.name;if(2<l.length&&"["===l[0]&&"]"===l[l.length-1])f=l.substr(1,l.length-2);else if(I(l,"data-amp-bind-")&&(f=l.substr(14),t.hasAttribute("["+f+"]"))){t=null;break a}if(f){if(h.qa.canBind(u,f)){t={property:f,expressionString:m.value};break a}f=B().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",f,u);Y(f,t)}t=null}t&&c.push(t)}return c}
function zc(a,b,c){return a.M.then(function(){Object.assign(c,a.w);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Nc(a,"amp-bind: Expression eval failed.");return b})}
function xc(a){return Z(a,"bind.evaluateBindings",[a.w]).then(function(b){var c=b.results,d=b.errors;Object.keys(d).forEach(function(b){var c=a.C[b];if(0<c.length){var e=d[b],h=B().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",b,e.message);h.stack=e.stack;Y(h,c[0])}});D().info("amp-bind","evaluation:",c);return c})}
function Mc(a,b){var c=void 0===c?null:c;var d=void 0===d?!0:d;var e={};a.G.forEach(function(a){var g=a.element;a=a.boundProperties;c&&!Qc(c,g)||a.forEach(function(a){var c=b[a.expressionString];if(void 0!==c){var f=a.property,h=tc[g.tagName];if(h&&h.includes(f))c=null;else{switch(f){case "text":f=g.textContent;c=String(c);h=f.trim()===c.trim();break;case "class":f=[];for(h=0;h<g.classList.length;h++){var l=g.classList[h];rc.test(l)||f.push(l)}l=[];Array.isArray(c)?l=c:"string"===typeof c?(h=c.trim(),
0<h.length&&(l=h.split(" "))):(h=B().createError('%s: "%s" is not a valid result for [class].',"amp-bind",c),Y(h,g));b:{h=f;var q=l;if(h.length!==q.length)h=!1;else{l=(Array.isArray(h)?h:w(h)).sort();q=(Array.isArray(q)?q:w(q)).sort();for(var C=0;C<h.length;C++)if(l[C]!==q[C]){h=!1;break b}h=!0}}break;default:f=g.getAttribute(f),h=!0===c?""===f:!1===c?null===f:"number"===typeof c?Number(f)===c:f===c}c=h?null:{expected:c,actual:f}}var v=c;if(v){c=g.tagName;f=a.property;a=a.expressionString;h=v.expected;
var r=v.actual;e[c+"["+f+"]"+h+":"+r]=!0;d&&B().warn("amp-bind","Default value ("+r+") does not match first result ("+(h+") for <"+c+" ["+f+']="')+(a+'">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.'))}}})});return Object.keys(e)}function Qc(a,b){for(var c=0;c<a.length;c++)if(a[c].contains(b))return!0;return!1}
function Rc(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,g=b[a.expressionString];void 0===g||lb(g,d)||(a.previousResult=g,c.push({boundProperty:a,newValue:g}))});return c}function yc(a,b,c){var d=[];a.G.forEach(function(e){if(!c.skipAmpState||"AMP-STATE"!==e.element.tagName)if(!c.constrain||c.constrain.some(function(a){return a.contains(e.element)})){var g=e.element,f=Rc(e.boundProperties,b);c.evaluateOnly||d.push(Sc(a,g,f))}});return Promise.all(d)}
function Sc(a,b,c){return 0===c.length?K():a.ka.mutateElement(b,function(){var d=F(),e,g;c.forEach(function(c){var f=c.boundProperty,h=c.newValue,u=f.property;a:{f=f.property;var l=b.tagName;switch(f){case "defaulttext":b.textContent=String(h);break;case "text":f=String(h);"TITLE"===l&&b.parentNode===a.I.document.head&&(a.I.document.title=f);"TEXTAREA"===l?b.value=f:b.textContent=f;break;case "class":f=[];for(l=0;l<b.classList.length;l++){var q=b.classList[l];rc.test(q)&&f.push(q)}Array.isArray(h)||
"string"===typeof h?b.setAttribute("class",f.concat(h).join(" ")):null===h?b.setAttribute("class",f.join(" ")):(f=B().createError('%s: "%s" is not a valid result for [class].',"amp-bind",h),Y(f,b));break;default:var C="INPUT"===l&&f in b,v=b.getAttribute(f);l=!1;if("boolean"===typeof h){if(C&&b[f]!==h&&(b[f]=h,l=!0),h&&""!==v?(b.setAttribute(f,""),l=!0):h||null===v||(b.removeAttribute(f),l=!0),l&&"OPTION"===b.tagName&&"selected"===f&&h&&S(a.h,"platform").isSafari()&&(q=bb(b,"select"))){var r=w(q.options).indexOf(b);
0<=r&&(q.selectedIndex=r)}}else if("object"===typeof h&&null!==h)l=!0;else if(h!==v)b:{v=String(h);try{q=b.tagName.toLowerCase();r=f.toLowerCase();var Ia="src"==r||"href"==r||"xlink:href"==r||"srcset"==r?mc(q,r,v):v;if(N(self.location)&&"a"===q&&"href"===r){var tb=b.getAttribute(r),ub="#"===Ia[0],vb=tb&&"#"===tb[0];ub&&!vb?(b.__AMP_ORIGINAL_TARGET_VALUE_||(b.__AMP_ORIGINAL_TARGET_VALUE_=b.getAttribute("target")),b.removeAttribute("target")):vb&&!ub&&b.setAttribute("target",b.__AMP_ORIGINAL_TARGET_VALUE_||
"_top")}C&&(b[r]=Ia);b.setAttribute(r,Ia);l=!0;break b}catch(Tc){l=B().createError('%s: "%s" is not a valid result for [%]',"amp-bind",v,f,Tc),Y(l,b)}l=!1}if(l){f={name:f,value:h};break a}}f=null}var Ja=f;Ja&&(d[Ja.name]=Ja.value,"width"==u?e="number"===typeof h&&isFinite(h)?Number(h):e:"height"==u&&(g="number"===typeof h&&isFinite(h)?Number(h):g));(h=sc[b.tagName])&&h[u]&&(u="OPTION"===b.tagName?bb(b,"SELECT"):b)&&(h=ob(a.I,"amp:form-value-change",null,{bubbles:!0}),u.dispatchEvent(h))});void 0===
e&&void 0===g||a.ka.forceChangeSize(b,g,e);if("function"===typeof b.mutatedAttributesCallback)try{b.mutatedAttributesCallback(d)}catch(h){var f=B().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(d),h);Y(f,b)}})}function Lc(a,b){b=b.target;var c=b.parentNode;c&&uc.includes(c.nodeName)||(D().info("amp-bind","dom_update:",b),Fc(a,[b],[b],"dom_update.end").then(function(){}))}
function Fc(a,b,c,d){d=void 0===d?"rescan.slow":d;var e=0;return Gc(a,c).then(function(c){e=c;return Kc(a,b)}).then(function(b){D().info("amp-bind","%s: delta=%s, total=%s",d,b-e,a.numberOfBindings())})}function Z(a,b,c){var d=a.h;a=a.I;if(d.Worker){var e=O(d);Ra(e,e,"amp-worker",Zb);b=$b(S(d,"amp-worker"),b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Nc(a,b,c){b=B().createError("%s %s",b,a.message);b.stack=a.stack;Y(b,c);return b}
function Bc(a){if(void 0===a)return null;try{return JSON.parse(JSON.stringify(a))}catch(b){D().error("amp-bind","Failed to copy JSON ("+a+") with error: "+b)}return null}
k.ya=function(a){if(a)if("string"==typeof a){var b=jb(this.w,a);B().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=B().assertElement(a),Uc(this,b)):B().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else B().info("amp-bind",this.w)};
function Uc(a,b){var c=Xb(a.G,function(a){return a.element==b});if(0>c)B().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.G[c].boundProperties;e.forEach(function(b){d.push(zc(a,b.expressionString,a.w))});Promise.all(d).then(function(a){var b=F();e.forEach(function(c,d){b[c.property]=a[d]});B().info("amp-bind",b)})}}k.xa=function(a){zc(this,a,this.w).then(function(a){B().info("amp-bind",a)})};k.Ha=function(){return this.M};k.Ja=function(){return this.U};(function(a){a.registerServiceForDoc("bind",vc);a.registerElement("amp-state",pb);a.registerElement("amp-bind-macro",va)})(self.AMP);
})});

//# sourceMappingURL=amp-bind-0.1.js.map
